name: watertap-ui-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cyipopt
  - reaktoro
  - pip
  - nodejs=20.9.0
  - flask
  - waitress
  - python-dotenv
  - pip:
    - -r backend/requirements.txt
    # - git+https://github.com/avdudchenko/reaktoro-pse.git@clean_up_of_major_refactor
    # - git+https://github.com/avdudchenko/watertap.git@adding_reaktoro_flowsheets_units
#    - git+https://github.com/watertap-org/watertap@workshop_tutorial
